# Exported from Render on 2024-06-08T15:55:04Z
services:
- type: web
  name: butchery-shop-api
  runtime: node
  repo: https://github.com/mm232323/butchery-shop-api
  plan: free
  envVars:
  - key: CI
    sync: false
  - key: CLI
    sync: false
  region: oregon
  buildCommand: npm install
  startCommand: npm start
version: "1"
